title: Moja Strona Jekyll
description: Projekt testowy na GitHub Pages
remote_theme: pages-themes/junior@v1.1.1
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
assets: [css/style.css]